### ISSUE TITLE
想问下怎么样处理有iframe的情况

### ISSUE THREAD

**Issue by goldmonkey163com** [asyne/cproto#7]
目前就发现不用装webdriver，不会是干净的chrome而带着扩展这些，这两个好处。。。
想问下，一个是如果想跟selenium一样find_element_by_id然后得到text
我查了下API，好像有个DOM.getOuterHTML
但是latest (tip-of-tree)版的需要三个参数（nodeId、backendNodeId、objectId），这个实在看不懂，stable (1.2)只有一个nodeID，但nodeID是整数，要怎么获取呢？
第二个是如果有iframe的话，selenium有switch_to_frame，那用devtool要怎么进？

**Comment by emansom** [comment]
I think the question is about how to query an element from the DOM using the DevTools protocol.
I found the answer inside the [lighthouse source code](https://github.com/GoogleChrome/lighthouse/blob/ab6aabde7a7311b773e75dab7e94c5b1f4b8263a/lighthouse-core/gather/driver.js#L696) (great resource btw) and [here](https://github.com/GoogleChrome/lighthouse/blob/ab6aabde7a7311b773e75dab7e94c5b1f4b8263a/lighthouse-core/lib/element.js)

First you execute an `DOM.getDocument()`, then you save the `root.nodeId` from the return value and use that as argument for `DOM.querySelector`

```python
result = DOM.getDocument()
rootNodeId = result.root.nodeId

elementRootId = DOM.querySelector(rootNodeId, '#some-element')
attributes = DOM.getAttributes(elementRootId)
```

**Comment by asyne** [comment]
@goldmonkey163com note that `DOM.getOuterHTML` has 3 *optional* parameters, you may only pass `nodeId` to it. According to the iframe, what's your specific use case?

**Comment by goldmonkey163com** [comment]
@emansom This is my code, but it suggests `TypeError: send_command() takes 1 positional argument but 3 were given`
`
from cproto import CProto
cp = CProto(host='127.0.0.1', port=9222)
cp.Page.navigate(url='https://www.hbooker.com/chapter/book_chapter_detail/100364049/')
result = cp.DOM.getDocument()
print(result)
rootNodeId = result['result']['root']['nodeId']
elementRootId = cp.DOM.querySelector(rootNodeId, '#J_BookCnt')
`

**Comment by goldmonkey163com** [comment]
@asyne I'm not clear about what `nodeId` is and how to get it. About iframe, this is what I do with selenium.
```
from selenium import webdriver
from time import sleep
driver = webdriver.Chrome()
driver.get("https://www.hbooker.com/chapter/book_chapter_detail/100364049/")
sleep(5)
driver.switch_to_frame(driver.find_element_by_tag_name("iframe"))
sleep(5)
driver.find_element_by_id('J_BookCnt').text
```
